### PR TITLE
Ui auth

### PR DESCRIPTION
**Pull request by NathanBland**
Running PR for user auth. This work is done, however due to user `CRUD` having issues.. it isn't viewed as being complete.

### CODE REVIEW

**Comment by crodeheaver** [comment]
`CURD`
haha

**Comment by NathanBland** [comment]
Can we merge this? Or is there a gaping issues with users you'd like to address?

**Comment by crodeheaver** [comment]
The only thing that I see that should be considered is that in your `app/admin/page/route.js` you have a model hook for `pages`. That should probably be done in `app/admin/page/index/route.js`.

Same thing goes for users. I'm not sure it should be in the top level route like that. Though I'm not necessarily sure it shouldn't be either.

**Comment by crodeheaver** [comment]
I can see the reasoning behind it, so I think it's fine.

**Pull request merged**
